packages:
  - apps/*
  - packages/*
  - tooling/*
  - examples/*

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - sharp
  - unrs-resolver

# from core - temporarily disabled for Next.js example setup
# trustPolicy: no-downgrade
# trustPolicyExclude:
#   - chokidar@4.0.3
#   - undici-types@6.21.0
#   - eslint-import-resolver-typescript@3.10.1


allowBuilds:
  esbuild: false
