packages:
  - apps/*
  - packages/*
  - examples/*

# Catalogs for shared dependency versions
# See: https://pnpm.io/catalogs
catalog:
  # ESLint and related plugins
  eslint: ^9.39.1
  '@eslint/js': ^9.39.1
  typescript-eslint: ^8.54.0
  eslint-config-prettier: ^10.1.1
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-turbo: ^2.7.1
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-react-refresh: ^0.4.24
  '@next/eslint-plugin-next': ^15.5.0
  
  # TypeScript
  typescript: ^5.9.3
  '@types/node': ^25.2.0
  '@types/react': ^19.2.5
  '@types/react-dom': ^19.2.3
  
  # Utilities
  globals: ^16.5.0

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - sharp
  - unrs-resolver

# from core - temporarily disabled for Next.js example setup
# trustPolicy: no-downgrade
# trustPolicyExclude:
#   - chokidar@4.0.3
#   - undici-types@6.21.0
#   - eslint-import-resolver-typescript@3.10.1

allowBuilds:
  esbuild: false
