packages:
  - apps/*
  - packages/*
  - tooling/*
  - examples/*

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - sharp
  - unrs-resolver

# from core
trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3


allowBuilds:
  esbuild: false